/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PcComponent;

import java.text.NumberFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author anthares101
 */
public class PcComponent extends javax.swing.JPanel {

    /**
     * Creates new form PcComponent
     */
    public PcComponent() {
        initComponents();
        
        this.visible = true;
        //Required for prize internationalitation
        this.setProductPrize(Double.parseDouble(this.jLabel3.getText()));
    }
    
    private boolean visible;
    private int componentType;
    
    public void setProductName(String name){
        this.jLabel2.setText(name);
    }
    
    public void setProductPrize(double prize){
        NumberFormat currency = NumberFormat.getCurrencyInstance();
        this.jLabel3.setText(currency.format(prize));
    }
    
    public void setRecomendationVisibility(boolean visible){
        this.visible = visible;
        this.jLabel5.setVisible(visible);
    }
    
    public void setProductImage(ImageIcon image){
        this.jLabel1.setIcon(image);
    }
    
    public void setComponentType(int type){
        this.componentType = type;
    }
    
    public String getProductName(){
        return this.jLabel2.getText();
    }
    
    public double getProductPrize(){
        NumberFormat currency = NumberFormat.getCurrencyInstance();
        Number prize = 0;
                
        try {
            prize = currency.parse(this.jLabel3.getText());
        } catch (ParseException ex) {
            Logger.getLogger(PcComponent.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return prize.doubleValue();
    }
    
    public boolean getRecomendationVisibility(){
        return this.visible;
    }
    
    public Icon getProductImage(){
        return this.jLabel1.getIcon();
    }
    
    public int getComponentType(){
        return this.componentType;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PcComponent/Image/questionMarkIcon.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 28)); // NOI18N
        jLabel2.setText("Componente");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 28)); // NOI18N
        jLabel3.setText("0.00");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 182, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PcComponent/Image/StartIcon.png"))); // NOI18N
        jLabel5.setText("Recomendado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
