/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Builder;

/**
 *
 * @author Sergi
 */
public class Builder extends javax.swing.JPanel {

    /**
     * Creates new form Builder
     */
    public Builder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cooler = new javax.swing.JLabel();
        gpu = new javax.swing.JLabel();
        psu = new javax.swing.JLabel();
        motherboard = new javax.swing.JLabel();
        box = new javax.swing.JLabel();
        tools = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(802, 756));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cooler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Builder/images/cooler.png"))); // NOI18N
        add(cooler, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        gpu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Builder/images/gpu.png"))); // NOI18N
        add(gpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        psu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Builder/images/psu.png"))); // NOI18N
        add(psu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, -1, -1));

        motherboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Builder/images/motherboard.png"))); // NOI18N
        add(motherboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        box.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Builder/images/box.png"))); // NOI18N
        add(box, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        tools.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Builder/images/tools.png"))); // NOI18N
        add(tools, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel box;
    private javax.swing.JLabel cooler;
    private javax.swing.JLabel gpu;
    private javax.swing.JLabel motherboard;
    private javax.swing.JLabel psu;
    private javax.swing.JLabel tools;
    // End of variables declaration//GEN-END:variables
}
